name: Train on CUDA

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'data/**'
      - 'requirements.txt'
      - '.github/workflows/train-cuda.yml'

jobs:
  train:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Set up CUDA (NVIDIA GPU)
        uses: Jimver/cuda-toolkit@v0.2.25
        id: cuda-toolkit
        with:
          log-file-suffix: '${{matrix.os}}.txt'
          cuda: '12.8.0'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
          pip install pandas matplotlib scikit-learn numpy transformers optuna tqdm 
      - name: Run training
        run: |
          python src/train.py
      - name: Upload SVG plot
        uses: actions/upload-artifact@v4
        with:
          name: training-plot
          path: store_predictor_best_training_plot.svg
      - name: Upload model checkpoint
        uses: actions/upload-artifact@v4
        with:
          name: model-checkpoint
          path: store_predictor_best.pth
